#!/usr/bin/env bash

function run {(
  export PORT="8000"
  export DATA_FOLDER="./data"
  export UPLOAD_SECRET="secret"
  deno run $(build-deno-flags) ./src/main.ts
)}

function build {(
  export DATA_FOLDER="${DATA_FOLDER:-"./data"}"
  mkdir -p ./out
  deno compile $(build-deno-flags) \
    --lite --output ./out/apt-repository \
    ./src/main.ts
)}

function lint {( cd "src" && deno --unstable lint )}
function compose {( cd "./docker" && docker-compose "${@}" )}

function docker-publish {(
  export VERSION_TAG="$(gen-version)"
  compose build
  compose push

  printf "%s: %s\n" \
    "Published version" "${VERSION_TAG}"
)}

function perf {(
  hey -n 10000 "${1}"
)}
function perf-local {(
  perf "http://localhost:8000"
)}
function perf-prod {(
  perf "https://apt.srk.bz"
)}

commands=(
  run build lint
  compose docker-publish
  perf perf-local perf-prod
)

function gen-version {( date +'%Y%m%d_%H%M%S' )}
function build-deno-flags {(
  printf "%s " \
    --unstable --allow-env --allow-run --allow-net \
    --import-map="./src/import_map.json" \
    --allow-read="${DATA_FOLDER},./src/templates" \
    --allow-write="${DATA_FOLDER}"
)}



function help {
    printf "%s\n" "Available commands:"
    printf " %s\n" "${commands[@]}" help
}

function run-command {
    command="$1"
    args=("${@:2}")
    for c in "${commands[@]}"; do
        if [ "$c" = "$command" ]; then
            ("$command" "${args[@]}")
            return
        fi
    done
    printf "%s\n" "Command '${command}' does not exist."
}

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
[ -z "${1:-""}" ] || [ "${1:-""}" = "help" ] && help && exit 0
run-command "${1}" "${@:2}"
